import Link from "next/link"
import { ArrowRight, BookOpen, CalendarDays } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

type BlogPost = { id: string; title: string; slug: string; excerpt: string | null; cover_image: string | null; created_at: string }

export function BlogHighlights({ posts }: { posts: BlogPost[] }) {
  return <Card className="overflow-hidden border-0 bg-white shadow-lg"><CardHeader className="flex flex-row items-center justify-between border-b border-gray-200 bg-[#32cd32]/10 p-4 sm:p-6"><CardTitle className="flex items-center gap-2 text-base text-gray-800 sm:text-lg"><BookOpen className="h-5 w-5 text-[#32cd32]" />Latest from Swopify</CardTitle><Link href="/blog" className="flex items-center gap-1 text-sm font-semibold text-[#073232] hover:text-[#32cd32]">View all posts<ArrowRight className="h-4 w-4" /></Link></CardHeader><CardContent className="p-4 sm:p-6">{posts.length ? <div className="grid gap-4 md:grid-cols-3">{posts.map((post) => <Link key={post.id} href={`/blog/${post.slug}`} className="group overflow-hidden rounded-xl border border-gray-200 bg-gray-50 transition hover:-translate-y-1 hover:border-[#32cd32]/50 hover:shadow-md">{post.cover_image ? <img src={post.cover_image} alt="" className="h-32 w-full object-cover" /> : <div className="flex h-32 items-center justify-center bg-gradient-to-br from-[#073232] to-[#0a4a4a]"><BookOpen className="h-10 w-10 text-[#32cd32]" /></div>}<div className="p-4"><h3 className="line-clamp-2 font-semibold text-[#073232] group-hover:text-[#32cd32]">{post.title}</h3><p className="mt-2 line-clamp-2 text-sm text-gray-600">{post.excerpt || "Read the latest Swopify update."}</p><span className="mt-3 flex items-center gap-1 text-xs text-gray-500"><CalendarDays className="h-3.5 w-3.5" />{new Date(post.created_at).toLocaleDateString()}</span></div></Link>)}</div> : <div className="rounded-xl border border-dashed border-gray-300 px-4 py-8 text-center"><BookOpen className="mx-auto h-8 w-8 text-gray-400" /><p className="mt-2 text-sm text-gray-600">No published posts yet.</p><Link href="/blog" className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-[#32cd32]">Visit the blog<ArrowRight className="h-4 w-4" /></Link></div>}</CardContent></Card>
}
